[package]
name = "jackrabbit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
rouille = "3.5.0"
serde = "1.0.137"
serde_derive = "1.0.137"
toml = "0.5.9"
